version: "3.9"

services:
  candidates_web:
    build: ./my-flask-app/candidates_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER:-user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-password}
      DB_NAME: ${MYSQL_DATABASE:-mydatabase}
    depends_on:
      - db

  voters_web:
    build: ./my-flask-app/voters_app
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER:-user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-password}
      DB_NAME: ${MYSQL_DATABASE:-mydatabase}
    depends_on:
      - db

  voting_web:
    build: ./my-flask-app/voting_app
    ports:
      - "2000:2000"
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER:-user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-password}
      DB_NAME: ${MYSQL_DATABASE:-mydatabase}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY:-a_default_secret_key}
    depends_on:
      - db

  db_viewer_web: # New service for the database viewer app
    build: ./my-flask-app/db_viewer_app
    ports:
      - "5555:5555" # Map host port 6000 to container port 6000
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER:-user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-password}
      DB_NAME: ${MYSQL_DATABASE:-mydatabase}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY:-another_default_secret_key}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY} # Pass encryption key
    depends_on:
      - db
      - candidates_web # Depends on other apps to ensure tables are created
      - voters_web
      - voting_web

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydatabase}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  db_data:
