from flask import Flask, render_template_string, request, redirect, url_for, flash, session
import os
import mysql.connector
import bcrypt
import random
import time
import re
import pyotp  # For MFA
import qrcode  # For QR code generation
from io import BytesIO
import base64  # For QR code encoding

app = Flask(__name__)
app.secret_key = os.getenv('FLASK_SECRET_KEY', 'a_super_secret_key_for_dev')
app.config['SESSION_COOKIE_SECURE'] = True
app.config['SESSION_COOKIE_HTTPONLY'] = True
app.config['SESSION_COOKIE_SAMESITE'] = 'Lax'
app.config['PERMANENT_SESSION_LIFETIME'] = 3600

# Database configurations
DB_HOST = os.getenv('DB_HOST', 'db')
DB_USER = os.getenv('DB_USER', 'user')
DB_PASSWORD = os.getenv('DB_PASSWORD', 'password')
DB_NAME = os.getenv('DB_NAME', 'mydatabase')
BLACKLISTED_IPS = []
RATE_LIMIT_WINDOW = 60
RATE_LIMIT_MAX = 5
rate_limit_dict = {}

# ---------------------- New MFA Templates ----------------------
MFA_SETUP_TEMPLATE = """
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Setup Two-Factor Authentication</title>
    <style>
        body { font-family: sans-serif; margin: 20px; background-color: #f0f8ff; color: #333; }
        .container { max-width: 500px; margin: auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h1 { color: #28a745; }
        .qrcode-container { text-align: center; margin: 20px 0; }
        .instructions { background-color: #e6ffe6; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
        form input[type="text"] { width: calc(100% - 22px); padding: 10px; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 4px; }
        form input[type="submit"] { background-color: #28a745; color: white; padding: 10px 15px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; }
        form input[type="submit"]:hover { background-color: #218838; }
        .error { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; padding: 10px; border-radius: 5px; margin-bottom: 15px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Setup Two-Factor Authentication (MFA)</h1>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="{{ category }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        <div class="instructions">
            <h3>Step 1: Scan the QR Code</h3>
            <p>Use an authenticator app (e.g., Google Authenticator, Authy) to scan the QR code below.</p>
            <p>If scanning fails, manually enter the secret key: <strong>{{ mfa_secret }}</strong></p>
        </div>

        <div class="qrcode-container">
            <img src="data:image/png;base64,{{ qr_code_base64 }}" alt="MFA QR Code" width="200">
        </div>

        <div class="instructions">
            <h3>Step 2: Enter Verification Code</h3>
            <p>Enter the 6-digit code generated by your authenticator app.</p>
        </div>

        <form method="POST" action="/setup_mfa">
            <label for="mfa_code">Verification Code:</label><br>
            <input type="text" id="mfa_code" name="mfa_code" required maxlength="6" placeholder="123456"><br><br>
            <input type="submit" value="Verify & Complete Setup">
        </form>
    </div>
</body>
</html>
"""

MFA_VERIFY_TEMPLATE = """
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Two-Factor Authentication</title>
    <style>
        body { font-family: sans-serif; margin: 20px; background-color: #f0f8ff; color: #333; }
        .container { max-width: 400px; margin: auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h1 { color: #28a745; }
        form input[type="text"] { width: calc(100% - 22px); padding: 10px; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 4px; }
        form input[type="submit"] { background-color: #28a745; color: white; padding: 10px 15px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; }
        form input[type="submit"]:hover { background-color: #218838; }
        .message { background-color: #d1ecf1; color: #0c5460; border: 1px solid #bee5eb; padding: 10px; border-radius: 5px; margin-bottom: 15px; }
        .error { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; padding: 10px; border-radius: 5px; margin-bottom: 15px; }
        .instructions { color: #666; font-size: 0.9em; margin-bottom: 15px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Two-Factor Authentication</h1>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="{{ category }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        <div class="instructions">
            Enter the 6-digit code from your authenticator app (e.g., Google Authenticator).
        </div>

        <form method="POST" action="/verify_mfa">
            <label for="mfa_code">Verification Code:</label><br>
            <input type="text" id="mfa_code" name="mfa_code" required maxlength="6" placeholder="123456"><br><br>
            <input type="submit" value="Verify Code">
        </form>
    </div>
</body>
</html>
"""

# ---------------------- Existing Templates ----------------------
ELEC_OFFICER_LOGIN_TEMPLATE = """
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Election Officer Login</title>
    <style>
        body { font-family: sans-serif; margin: 20px; background-color: #f0f8ff; color: #333; }
        .container { max-width: 400px; margin: auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h1 { color: #28a745; }
        form { padding: 15px; border: 1px solid #ccf; border-radius: 5px; background-color: #f7fcff; }
        form input[type="email"], form input[type="password"], form input[type="text"] { width: calc(100% - 22px); padding: 10px; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 4px; }
        form input[type="submit"] { background-color: #28a745; color: white; padding: 10px 15px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; }
        form input[type="submit"]:hover { background-color: #218838; }
        .message { background-color: #d1ecf1; color: #0c5460; border: 1px solid #bee5eb; padding: 10px; border-radius: 5px; margin-bottom: 15px; }
        .error { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; padding: 10px; border-radius: 5px; margin-bottom: 15px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Election Officer Login</h1>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="{{ category }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <label for="email">Email:</label><br>
            <input type="email" id="email" name="email" required><br><br>
            <label for="password">Password:</label><br>
            <input type="password" id="password" name="password" required><br><br>
            <label for="captcha">CAPTCHA: {{ captcha_question }}</label><br>
            <input type="text" id="captcha" name="captcha" required><br><br>
            <input type="submit" value="Login">
        </form>
    </div>
</body>
</html>
"""

VOTERS_TEMPLATE = """
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Voter Registration</title>
    <style>
        body { font-family: sans-serif; margin: 20px; background-color: #f0f8ff; color: #333; }
        .container { max-width: 800px; margin: auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h1, h2 { color: #28a745; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #e6ffe6; }
        form { margin-top: 20px; padding: 15px; border: 1px solid #ccf; border-radius: 5px; background-color: #f7fcff; }
        form input[type="text"], form input[type="email"], form input[type="number"] { width: calc(100% - 22px); padding: 10px; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 4px; }
        form select { width: calc(100% - 22px); padding: 10px; margin-bottom: 10px; border: 1px solid #ccc; border-radius: 4px; }
        form input[type="submit"] { background-color: #28a745; color: white; padding: 10px 15px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; }
        form input[type="submit"]:hover { background-color: #218838; }
        .action-buttons { display: flex; gap: 5px; }
        .edit-button { background-color: #ffc107; color: #212529; padding: 5px 10px; border: none; border-radius: 4px; cursor: pointer; }
        .edit-button:hover { background-color: #e0a800; }
        .delete-form { display: inline; }
        .delete-button { background-color: #dc3545; color: white; padding: 5px 10px; border: none; border-radius: 4px; cursor: pointer; }
        .delete-button:hover { background-color: #c82333; }
        .approve-button { background-color: #28a745; color: white; padding: 5px 10px; border: none; border-radius: 4px; cursor: pointer; }
        .approve-button:hover { background-color: #218838; }
        .message { background-color: #d1ecf1; color: #0c5460; border: 1px solid #bee5eb; padding: 10px; border-radius: 5px; margin-bottom: 15px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Voter Registration Application</h1>
        <p>Welcome, {{ session['elec_officer_name'] }}! <a class="logout-link" href="/logout">Logout</a></p>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="{{ category }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {% if edit_voter %}
        <h2>Edit Voter (ID: {{ edit_voter[0] }})</h2>
        <form method="POST" action="/edit/{{ edit_voter[0] }}">
            <label for="name">Name:</label><br>
            <input type="text" id="name" name="name" value="{{ edit_voter[1] }}" required><br><br>
            <label for="email">Email:</label><br>
            <input type="email" id="email" name="email" value="{{ edit_voter[2] }}" required><br><br>
            <label for="age">Age:</label><br>
            <input type="number" id="age" name="age" value="{{ edit_voter[3] }}" required min="18"><br><br>
            <label for="sex">Sex:</label><br>
            <select id="sex" name="sex" required>
                <option value="Male" {% if edit_voter[4] == 'Male' %}selected{% endif %}>Male</option>
                <option value="Female" {% if edit_voter[4] == 'Female' %}selected{% endif %}>Female</option>
                <option value="Other" {% if edit_voter[4] == 'Other' %}selected{% endif %}>Other</option>
            </select><br><br>
            <label for="status">Status:</label><br>
            <select id="status" name="status" required>
                <option value="submitted" {% if edit_voter[5] == 'submitted' %}selected{% endif %}>Submitted</option>
                <option value="accepted" {% if edit_voter[5] == 'accepted' %}selected{% endif %}>Accepted</option>
                <option value="rejected" {% if edit_voter[5] == 'rejected' %}selected{% endif %}>Rejected</option>
            </select><br><br>
            <input type="submit" value="Update Voter">
            <a href="/" style="margin-left: 10px;">Cancel</a>
        </form>
        {% else %}
        <h2>Current Registered Voters</h2>
        {% if voters %}
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Age</th>
                    <th>Sex</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for voter in voters %}
                <tr>
                    <td>{{ voter[0] }}</td>
                    <td>{{ voter[1] }}</td>
                    <td>{{ voter[2] }}</td>
                    <td>{{ voter[3] }}</td>
                    <td>{{ voter[4] }}</td>
                    <td>{{ voter[5] }}</td>
                    <td class="action-buttons">
                        {% if voter[5] == 'submitted' %}
                        <form class="delete-form" method="POST" action="/approve/{{ voter[0] }}">
                            <input type="submit" value="Approve" class="approve-button">
                        </form>
                        {% endif %}
                        <form class="delete-form" method="GET" action="/edit/{{ voter[0] }}">
                            <input type="submit" value="Edit" class="edit-button">
                        </form>
                        <form class="delete-form" method="POST" action="/delete/{{ voter[0] }}">
                            <input type="submit" value="Delete" class="delete-button">
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No voters registered yet.</p>
        {% endif %}
        {% endif %}
    </div>
</body>
</html>
"""

# ---------------------- MFA Utility Functions ----------------------
def generate_mfa_secret():
    """Generate a 16-bit Base32 secret key compliant with TOTP standards"""
    return pyotp.random_base32()

def generate_mfa_qr_code(secret, email):
    """Generate MFA binding QR code (returns Base64 encoding)"""
    totp_uri = pyotp.totp.TOTP(secret).provisioning_uri(
        name=email,
        issuer_name="ElectionOfficerSystem"
    )
    qr = qrcode.QRCode(version=1, box_size=10, border=4)
    qr.add_data(totp_uri)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buffer = BytesIO()
    img.save(buffer, format="PNG")
    return base64.b64encode(buffer.getvalue()).decode('utf-8')

def verify_mfa_code(secret, code):
    """Verify MFA verification code (allows ±30 seconds error)"""
    totp = pyotp.TOTP(secret)
    return totp.verify(code, valid_window=1)

# ---------------------- Database & Core Functions ----------------------
def get_db_connection():
    return mysql.connector.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASSWORD,
        database=DB_NAME
    )

def init_db():
    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        # Update elec_officers table: add MFA fields
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS elec_officers (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                email VARCHAR(255) NOT NULL UNIQUE,
                password VARCHAR(255) NOT NULL,
                role ENUM('elec_officer') DEFAULT 'elec_officer',
                mfa_secret VARCHAR(255) NULL,  -- Store MFA secret
                mfa_enabled BOOLEAN DEFAULT FALSE  -- MFA enabled flag
            );
        """)
        # Update voters table (add age/sex if not exist)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS voters (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                email VARCHAR(255) NOT NULL UNIQUE,
                status ENUM('submitted', 'accepted', 'rejected') DEFAULT 'submitted'
            );
        """)
        cursor.execute("SHOW COLUMNS FROM voters LIKE 'age'")
        if not cursor.fetchone():
            cursor.execute("ALTER TABLE voters ADD COLUMN age INT NOT NULL DEFAULT 18")
        cursor.execute("SHOW COLUMNS FROM voters LIKE 'sex'")
        if not cursor.fetchone():
            cursor.execute("ALTER TABLE voters ADD COLUMN sex ENUM('Male', 'Female', 'Other') NOT NULL DEFAULT 'Other'")
        # Update audit_logs table (keep existing)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS audit_logs (
                id INT AUTO_INCREMENT PRIMARY KEY,
                user_id INT,
                action VARCHAR(255),
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                ip VARCHAR(45),
                details TEXT
            );
        """)
        # Add MFA fields to existing elec_officers table (if missing)
        cursor.execute("SHOW COLUMNS FROM elec_officers LIKE 'mfa_secret'")
        if not cursor.fetchone():
            cursor.execute("ALTER TABLE elec_officers ADD COLUMN mfa_secret VARCHAR(255) NULL")
        cursor.execute("SHOW COLUMNS FROM elec_officers LIKE 'mfa_enabled'")
        if not cursor.fetchone():
            cursor.execute("ALTER TABLE elec_officers ADD COLUMN mfa_enabled BOOLEAN DEFAULT FALSE")
        
        conn.commit()
        print("Database initialized successfully (MFA fields added to elec_officers)")
    except Exception as e:
        print(f"Error initializing database: {e}")
    finally:
        if conn:
            conn.close()

def require_elec_officer_login(f):
    def decorated_function(*args, **kwargs):
        if 'elec_officer_id' not in session:
            flash("Please log in to access this page", 'error')
            return redirect(url_for('elec_officer_login'))
        return f(*args, **kwargs)
    decorated_function.__name__ = f.__name__
    return decorated_function

@app.before_request
def before_first_request():
    init_db()

def validate_password_strength(password):
    if len(password) < 8 or not re.search("[A-Z]", password) or not re.search("[a-z]", password) or not re.search("\d", password) or not re.search("[!@#$%^&*]", password):
        return False
    return True

def generate_captcha():
    num1 = random.randint(1, 10)
    num2 = random.randint(1, 10)
    operation = random.choice(['+', '-'])
    question = f"What is {num1} {operation} {num2}?"
    answer = num1 + num2 if operation == '+' else num1 - num2
    return question, str(answer)

def log_audit(user_id, action, ip, details=''):
    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("INSERT INTO audit_logs (user_id, action, ip, details) VALUES (%s, %s, %s, %s)", (user_id, action, ip, details))
        conn.commit()
    except Exception as e:
        print(f"Error logging audit: {e}")
    finally:
        if conn:
            conn.close()

def is_ip_blacklisted(ip):
    return ip in BLACKLISTED_IPS

def check_rate_limit(ip):
    now = time.time()
    if ip in rate_limit_dict:
        count, last_time = rate_limit_dict[ip]
        if now - last_time < RATE_LIMIT_WINDOW:
            if count >= RATE_LIMIT_MAX:
                return False
            rate_limit_dict[ip] = (count + 1, last_time)
            return True
        rate_limit_dict[ip] = (1, now)
        return True
    rate_limit_dict[ip] = (1, now)
    return True

# ---------------------- MFA Routes ----------------------
@app.route('/setup_mfa', methods=['GET', 'POST'])
def setup_mfa():
    """MFA setup page (for first login without MFA)"""
    if 'temp_officer_id' not in session or 'temp_mfa_secret' not in session:
        flash("Please log in first", 'error')
        return redirect(url_for('elec_officer_login'))
    
    mfa_secret = session['temp_mfa_secret']
    officer_email = session.get('temp_officer_email', 'officer@example.com')
    
    if request.method == 'POST':
        mfa_code = request.form['mfa_code'].strip()
        if verify_mfa_code(mfa_secret, mfa_code):
            # Save MFA secret and enable MFA
            conn = None
            try:
                conn = get_db_connection()
                cursor = conn.cursor()
                cursor.execute("""
                    UPDATE elec_officers 
                    SET mfa_secret = %s, mfa_enabled = TRUE 
                    WHERE id = %s
                """, (mfa_secret, session['temp_officer_id']))
                conn.commit()
                # Create official session
                session['elec_officer_id'] = session['temp_officer_id']
                session['elec_officer_name'] = session['temp_officer_name']
                # Clear temporary data
                session.pop('temp_officer_id', None)
                session.pop('temp_officer_name', None)
                session.pop('temp_mfa_secret', None)
                session.pop('temp_officer_email', None)
                log_audit(session['elec_officer_id'], 'mfa_setup_success', request.remote_addr, "Completed MFA setup")
                flash("MFA setup successful! You are now logged in.", 'message')
                return redirect(url_for('index'))
            except Exception as e:
                log_audit(session['temp_officer_id'], 'mfa_setup_failed', request.remote_addr, str(e))
                flash(f"Failed to set up MFA: {e}", 'error')
                return redirect(url_for('elec_officer_login'))
            finally:
                if conn:
                    conn.close()
        else:
            flash("Invalid verification code. Please try again.", 'error')
    
    # Generate QR code for GET request
    qr_code_base64 = generate_mfa_qr_code(mfa_secret, officer_email)
    return render_template_string(
        MFA_SETUP_TEMPLATE,
        mfa_secret=mfa_secret,
        qr_code_base64=qr_code_base64
    )

@app.route('/verify_mfa', methods=['GET', 'POST'])
def verify_mfa():
    """MFA verification page (for users with MFA enabled)"""
    if 'temp_officer_id' not in session or 'temp_mfa_secret' not in session:
        flash("Please log in first", 'error')
        return redirect(url_for('elec_officer_login'))
    
    if request.method == 'POST':
        mfa_code = request.form['mfa_code'].strip()
        if verify_mfa_code(session['temp_mfa_secret'], mfa_code):
            # Verification success: log in
            session['elec_officer_id'] = session['temp_officer_id']
            session['elec_officer_name'] = session['temp_officer_name']
            # Clear temporary data
            session.pop('temp_officer_id', None)
            session.pop('temp_officer_name', None)
            session.pop('temp_mfa_secret', None)
            log_audit(session['elec_officer_id'], 'mfa_verify_success', request.remote_addr, "MFA verification passed")
            flash("Verification successful! You are now logged in.", 'message')
            return redirect(url_for('index'))
        else:
            log_audit(session['temp_officer_id'], 'mfa_verify_failed', request.remote_addr, "Invalid MFA code")
            flash("Invalid verification code. Please try again.", 'error')
    
    return render_template_string(MFA_VERIFY_TEMPLATE)

# ---------------------- Existing Routes (Updated for MFA) ----------------------
@app.route('/login', methods=['GET', 'POST'])
def elec_officer_login():
    ip = request.remote_addr
    if is_ip_blacklisted(ip) or not check_rate_limit(ip):
        log_audit(None, 'access_denied', ip, details="Rate limit or blacklist violation")
        flash("Access denied due to rate limit or blacklist", 'error')
        return render_template_string(ELEC_OFFICER_LOGIN_TEMPLATE, captcha_question="")
    
    if request.method == 'POST':
        email = request.form['email'].strip()
        password = request.form['password']
        captcha_response = request.form['captcha']
        captcha_answer = session.get('captcha_answer')
        
        if captcha_response != captcha_answer:
            flash("CAPTCHA incorrect. Please try again.", 'error')
            log_audit(None, 'failed_login', ip, details="Incorrect CAPTCHA")
            captcha_question, captcha_answer = generate_captcha()
            session['captcha_answer'] = captcha_answer
            return render_template_string(ELEC_OFFICER_LOGIN_TEMPLATE, captcha_question=captcha_question)

        conn = None
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            # Query officer with MFA fields
            cursor.execute("""
                SELECT id, name, password, role, mfa_enabled, mfa_secret 
                FROM elec_officers WHERE email = %s
            """, (email,))
            officer = cursor.fetchone()
            if officer:
                officer_id, officer_name, hashed_password, role, mfa_enabled, mfa_secret = officer
                if bcrypt.checkpw(password.encode('utf-8'), hashed_password.encode('utf-8')):
                    if role == 'elec_officer':
                        # Case 1: MFA not enabled -> redirect to setup
                        if not mfa_enabled:
                            temp_mfa_secret = generate_mfa_secret()
                            # Store temporary data in session
                            session['temp_officer_id'] = officer_id
                            session['temp_officer_name'] = officer_name
                            session['temp_mfa_secret'] = temp_mfa_secret
                            session['temp_officer_email'] = email
                            log_audit(officer_id, 'login_mfa_setup_redirect', ip, "MFA not enabled, redirect to setup")
                            return redirect(url_for('setup_mfa'))
                        # Case 2: MFA enabled -> redirect to verify
                        else:
                            session['temp_officer_id'] = officer_id
                            session['temp_officer_name'] = officer_name
                            session['temp_mfa_secret'] = mfa_secret  # Use existing secret
                            log_audit(officer_id, 'login_mfa_verify_redirect', ip, "MFA enabled, redirect to verify")
                            return redirect(url_for('verify_mfa'))
                    else:
                        log_audit(officer_id, 'failed_login_role', ip, details=f"Invalid role for {email}")
                        flash("Invalid election officer role", 'error')
                else:
                    log_audit(None, 'failed_login_password', ip, details=f"Invalid password for {email}")
                    flash("Invalid credentials", 'error')
            else:
                log_audit(None, 'failed_login_email', ip, details=f"Invalid email {email}")
                flash("Invalid credentials", 'error')
            
            # Regenerate CAPTCHA for failed login
            captcha_question, captcha_answer = generate_captcha()
            session['captcha_answer'] = captcha_answer
            return render_template_string(ELEC_OFFICER_LOGIN_TEMPLATE, captcha_question=captcha_question)
        except Exception as e:
            log_audit(None, 'failed_login_error', ip, details=str(e))
            flash(f"Error: {e}", 'error')
            captcha_question, captcha_answer = generate_captcha()
            session['captcha_answer'] = captcha_answer
            return render_template_string(ELEC_OFFICER_LOGIN_TEMPLATE, captcha_question=captcha_question)
        finally:
            if conn:
                conn.close()
    else:
        # GET request: generate CAPTCHA
        captcha_question, captcha_answer = generate_captcha()
        session['captcha_answer'] = captcha_answer
        return render_template_string(ELEC_OFFICER_LOGIN_TEMPLATE, captcha_question=captcha_question)

@app.route('/')
@require_elec_officer_login
def index():
    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("SELECT id, name, email, age, sex, status FROM voters ORDER BY FIELD(status, 'submitted', 'accepted', 'rejected'), id")
        voters = cursor.fetchall()
        log_audit(session['elec_officer_id'], 'view_voters', request.remote_addr)
        return render_template_string(VOTERS_TEMPLATE, voters=voters, message="Welcome to the Voter Registration App!")
    except Exception as e:
        log_audit(session['elec_officer_id'], 'view_voters_error', request.remote_addr, details=str(e))
        flash(f"Error loading voters: {e}", 'error')
        return render_template_string(VOTERS_TEMPLATE, voters=[], message=f"Error loading voters: {e}")
    finally:
        if conn:
            conn.close()

@app.route('/edit/<int:voter_id>', methods=['GET', 'POST'])
@require_elec_officer_login
def edit_voter(voter_id):
    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        if request.method == 'POST':
            name = request.form['name']
            email = request.form['email']
            age = request.form['age']
            sex = request.form['sex']
            status = request.form['status']
            cursor.execute("UPDATE voters SET name = %s, email = %s, age = %s, sex = %s, status = %s WHERE id = %s", (name, email, age, sex, status, voter_id))
            conn.commit()
            log_audit(session['elec_officer_id'], 'edit_voter', request.remote_addr, details=f"Edited voter ID {voter_id}")
            flash("Voter updated successfully", 'message')
            return redirect(url_for('index'))
        else: # GET request to show edit form
            cursor.execute("SELECT id, name, email, age, sex, status FROM voters WHERE id = %s", (voter_id,))
            voter = cursor.fetchone()
            if voter:
                log_audit(session['elec_officer_id'], 'view_edit_voter', request.remote_addr, details=f"Viewing edit form for voter ID {voter_id}")
                return render_template_string(VOTERS_TEMPLATE, edit_voter=voter, message=f"Editing Voter ID: {voter_id}")
            else:
                log_audit(session['elec_officer_id'], 'view_edit_voter_error', request.remote_addr, details=f"Voter ID {voter_id} not found")
                flash("Voter not found", 'error')
                return redirect(url_for('index'))
    except Exception as e:
        log_audit(session['elec_officer_id'], 'edit_voter_error', request.remote_addr, details=str(e))
        flash(f"Error editing voter: {e}", 'error')
        return redirect(url_for('index'))
    finally:
        if conn:
            conn.close()

@app.route('/approve/<int:voter_id>', methods=['POST'])
@require_elec_officer_login
def approve_voter(voter_id):
    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("UPDATE voters SET status = 'accepted' WHERE id = %s", (voter_id,))
        conn.commit()
        log_audit(session['elec_officer_id'], 'approve_voter', request.remote_addr, details=f"Approved voter ID {voter_id}")
        flash("Voter approved successfully", 'message')
    except Exception as e:
        log_audit(session['elec_officer_id'], 'approve_voter_error', request.remote_addr, details=str(e))
        flash(f"Error approving voter: {e}", 'error')
    finally:
        if conn:
            conn.close()
    return redirect(url_for('index'))

@app.route('/delete/<int:voter_id>', methods=['POST'])
@require_elec_officer_login
def delete_voter(voter_id):
    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("DELETE FROM voters WHERE id = %s", (voter_id,))
        conn.commit()
        log_audit(session['elec_officer_id'], 'delete_voter', request.remote_addr, details=f"Deleted voter ID {voter_id}")
        flash("Voter deleted successfully", 'message')
    except Exception as e:
        log_audit(session['elec_officer_id'], 'delete_voter_error', request.remote_addr, details=str(e))
        print(f"Error deleting voter: {e}")
    finally:
        if conn:
            conn.close()
    return redirect(url_for('index'))

@app.route('/logout')
def logout():
    log_audit(session.get('elec_officer_id'), 'logout', request.remote_addr)
    session.clear()
    flash("Logged out successfully", 'message')
    return redirect(url_for('elec_officer_login'))

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=4000, debug=True)